theme: minima
title: Senses
author: sengleson
email: notavalidaddress@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  So this is where we SEO my unique fancy github page let's see if it works

# social links
twitter_username: nah
github_username:  sengleson-r7

show_excerpts: true # set to false to remove excerpts on the homepage
